<?php require_once __DIR__ . '/common.php';
$exams=$pdo->prepare("SELECT * FROM exams WHERE class_id=? AND status='published'");$exams->execute([$student['class_id']]);$exams=$exams->fetchAll();
$messages=$pdo->prepare('SELECT * FROM messages WHERE receiver_user_id=? ORDER BY id DESC LIMIT 5');$messages->execute([$_SESSION['user']['id']]);$messages=$messages->fetchAll();
$notices=$pdo->query("SELECT * FROM notices WHERE audience IN ('all','students') AND (expires_at IS NULL OR expires_at>=CURDATE()) ORDER BY id DESC LIMIT 5")->fetchAll();
$events=$pdo->query('SELECT * FROM events ORDER BY event_date DESC LIMIT 5')->fetchAll();
$results=$pdo->prepare('SELECT ea.*,e.title FROM exam_attempts ea JOIN exams e ON e.id=ea.exam_id WHERE student_id=? ORDER BY ea.id DESC LIMIT 5');$results->execute([$student['id']]);$results=$results->fetchAll();
include __DIR__ . '/../templates/header.php'; include __DIR__ . '/../templates/sidebar.php'; ?>
<h4>Student Dashboard</h4>
<div class="row"><div class="col-md-6"><div class="card mb-3"><div class="card-header">Available Exams</div><ul class="list-group list-group-flush"><?php foreach($exams as $e):?><li class="list-group-item d-flex justify-content-between"><span><?=e($e['title'])?></span><a href="instructions.php?exam_id=<?=$e['id']?>" class="btn btn-sm btn-primary">Start</a></li><?php endforeach;?></ul></div><div class="card"><div class="card-header">Recent Results</div><ul class="list-group list-group-flush"><?php foreach($results as $r):?><li class="list-group-item"><?=e($r['title'])?> - <?=$r['score']?>/<?=$r['total']?></li><?php endforeach;?></ul></div></div>
<div class="col-md-6"><div class="card mb-3"><div class="card-header">Notices</div><ul class="list-group list-group-flush"><?php foreach($notices as $n):?><li class="list-group-item"><?=e($n['title'])?></li><?php endforeach;?></ul></div><div class="card mb-3"><div class="card-header">Events</div><ul class="list-group list-group-flush"><?php foreach($events as $n):?><li class="list-group-item"><?=e($n['title'])?> (<?=e($n['event_date'])?>)</li><?php endforeach;?></ul></div><div class="card"><div class="card-header">Messages</div><ul class="list-group list-group-flush"><?php foreach($messages as $m):?><li class="list-group-item"><?=e($m['subject'])?></li><?php endforeach;?></ul></div></div></div>
<?php include __DIR__ . '/../templates/footer.php'; ?>
