<?php require_once __DIR__ . '/common.php';
$classes=$pdo->query('SELECT * FROM classes')->fetchAll(); $subjects=$pdo->query('SELECT * FROM subjects')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $pdo->prepare('INSERT INTO exams(title,class_id,subject_id,duration_minutes,total_questions,start_time,end_time,instructions,shuffle_questions,shuffle_options,allow_review,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')
 ->execute([trim($_POST['title']),(int)$_POST['class_id'],(int)$_POST['subject_id'],(int)$_POST['duration_minutes'],(int)$_POST['total_questions'],$_POST['start_time']?:null,$_POST['end_time']?:null,trim($_POST['instructions']),(int)!empty($_POST['shuffle_questions']),(int)!empty($_POST['shuffle_options']),(int)!empty($_POST['allow_review']),'draft',$_SESSION['user']['id']]);
}
if(isset($_GET['publish'])) $pdo->prepare("UPDATE exams SET status='published' WHERE id=?")->execute([(int)$_GET['publish']]);
if(isset($_GET['close'])) $pdo->prepare("UPDATE exams SET status='closed' WHERE id=?")->execute([(int)$_GET['close']]);
$rows=$pdo->query('SELECT e.*,c.name class_name,s.name subject_name FROM exams e JOIN classes c ON c.id=e.class_id JOIN subjects s ON s.id=e.subject_id ORDER BY e.id DESC')->fetchAll();
include __DIR__ . '/../templates/header.php'; include __DIR__ . '/../templates/sidebar.php'; ?>
<h4>Exam Management</h4>
<form method="post" class="row g-2 mb-3"><div class="col-md-2"><input name="title" class="form-control" placeholder="Title" required></div><div class="col-md-1"><select name="class_id" class="form-select"><?php foreach($classes as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-md-2"><select name="subject_id" class="form-select"><?php foreach($subjects as $s):?><option value="<?=$s['id']?>"><?=e($s['name'])?></option><?php endforeach;?></select></div><div class="col-md-1"><input name="duration_minutes" type="number" class="form-control" placeholder="Mins" required></div><div class="col-md-1"><input name="total_questions" type="number" class="form-control" placeholder="Total" required></div><div class="col-md-2"><input type="datetime-local" name="start_time" class="form-control"></div><div class="col-md-2"><input type="datetime-local" name="end_time" class="form-control"></div><div class="col-md-12"><textarea name="instructions" class="form-control" placeholder="Instructions"></textarea></div><div class="col-md-4"><div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="shuffle_questions"><label class="form-check-label">Shuffle Q</label></div><div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="shuffle_options"><label class="form-check-label">Shuffle Opt</label></div><div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="allow_review" checked><label class="form-check-label">Allow Review</label></div></div><div class="col-md-2"><button class="btn btn-primary">Create Exam</button></div></form>
<table class="table table-sm"><tr><th>Title</th><th>Class</th><th>Subject</th><th>Status</th><th>Actions</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['title'])?></td><td><?=e($r['class_name'])?></td><td><?=e($r['subject_name'])?></td><td><?=e($r['status'])?></td><td><a class="btn btn-sm btn-secondary" href="exam_builder.php?exam_id=<?=$r['id']?>">Builder</a> <a class="btn btn-sm btn-info" href="exam_instructions.php?exam_id=<?=$r['id']?>">Instructions</a> <a class="btn btn-sm btn-success" href="?publish=<?=$r['id']?>">Publish</a> <a class="btn btn-sm btn-dark" href="?close=<?=$r['id']?>">Close</a></td></tr><?php endforeach;?></table>
<?php include __DIR__ . '/../templates/footer.php'; ?>
